name: Branch QA
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**/README.md"
      - "python/**"
  workflow_dispatch:

jobs:
  dependencies:
    uses: ./.github/workflows/dependabot.yml
    secrets: inherit #pragma: allowlist secret
  lint-and-test:
    needs: [dependencies]
    if: ${{!contains(github.event.head_commit.message, 'chore(deps-dev)')}}
    name: Workspace
    strategy:
      matrix:
        workspace: [model, designer, runner]
    uses: ./.github/workflows/lint-and-test.yml
    with:
      workspace: ${{ matrix.workspace }}

  build-designer:
    name: Designer
    uses: ./.github/workflows/build.yml
    with:
      app: designer
    secrets: inherit #pragma: allowlist secret

  build-runner:
    name: Runner
    uses: ./.github/workflows/build.yml
    with:
      app: runner
    secrets: inherit #pragma: allowlist secret

  smoke-test:
    needs: [build-runner, build-designer]
    uses: ./.github/workflows/smoke-test.yml
    with:
      runner-cache-ref: ${{needs.build-runner.outputs.tag}}
      designer-cache-ref: ${{needs.build-designer.outputs.tag}}
    secrets: inherit #pragma: allowlist secret
